name: NASA Project CI
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Change to directory to NASA Project
              run: cd 9\ -\ NASA\ Project/
            
            - name: Use Node.js version 20
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            
            - name: Install dependencies
              run: npm install
            
            - name: Build project
              run: run build --prefix client
